/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookRouteImport } from './routes/book'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'
import { Route as AppCouponsRouteImport } from './routes/app.coupons'
import { Route as AppFulfillmentRouteImport } from './routes/app.fulfillment'
import { Route as AppMyOrdersRouteImport } from './routes/app.my-orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOfferRouteImport } from './routes/app.offer'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as StaffAdminRouteImport } from './routes/staff.admin'
import { Route as StaffForgotPasswordRouteImport } from './routes/staff.forgot-password'
import { Route as AppAdminAccountAuditRouteImport } from './routes/app.admin.account-audit'
import { Route as AppAdminAccountsRouteImport } from './routes/app.admin.accounts'
import { Route as AppAdminAuditLogRouteImport } from './routes/app.admin.audit-log'
import { Route as AppAdminDeliveryPointsRouteImport } from './routes/app.admin.delivery-points'
import { Route as AppAdminEmailRecordsRouteImport } from './routes/app.admin.email-records'
import { Route as AppAdminEmployeesRouteImport } from './routes/app.admin.employees'
import { Route as AppAdminMailboxRouteImport } from './routes/app.admin.mailbox'
import { Route as AppAdminPasswordResetsRouteImport } from './routes/app.admin.password-resets'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminTeamRouteImport } from './routes/app.admin.team'
import { Route as AppOperatorIndexRouteImport } from './routes/app.operator.index'
import { Route as AppOperatorNewBatchRouteImport } from './routes/app.operator.new-batch'
import { Route as AppOperatorPublishRouteImport } from './routes/app.operator.publish'
import { Route as AppOperatorPublishRecordsRouteImport } from './routes/app.operator.publish-records'
import { Route as AppOrderNewRouteImport } from './routes/app.order.new'
import { Route as AppOrderConfirmationOrderIdRouteImport } from './routes/app.order.confirmation.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsRoute = AppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppRoute,
} as any)
const AppFulfillmentRoute = AppFulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => AppRoute,
} as any)
const AppMyOrdersRoute = AppMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferRoute = AppOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const StaffAdminRoute = StaffAdminRouteImport.update({
  id: '/staff/admin',
  path: '/staff/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffForgotPasswordRoute = StaffForgotPasswordRouteImport.update({
  id: '/staff/forgot-password',
  path: '/staff/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAccountAuditRoute = AppAdminAccountAuditRouteImport.update({
  id: '/admin/account-audit',
  path: '/admin/account-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAccountsRoute = AppAdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDeliveryPointsRoute = AppAdminDeliveryPointsRouteImport.update({
  id: '/admin/delivery-points',
  path: '/admin/delivery-points',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailRecordsRoute = AppAdminEmailRecordsRouteImport.update({
  id: '/admin/email-records',
  path: '/admin/email-records',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMailboxRoute = AppAdminMailboxRouteImport.update({
  id: '/admin/mailbox',
  path: '/admin/mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPasswordResetsRoute = AppAdminPasswordResetsRouteImport.update({
  id: '/admin/password-resets',
  path: '/admin/password-resets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTeamRoute = AppAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorIndexRoute = AppOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorNewBatchRoute = AppOperatorNewBatchRouteImport.update({
  id: '/operator/new-batch',
  path: '/operator/new-batch',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorPublishRoute = AppOperatorPublishRouteImport.update({
  id: '/operator/publish',
  path: '/operator/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorPublishRecordsRoute =
  AppOperatorPublishRecordsRouteImport.update({
    id: '/operator/publish-records',
    path: '/operator/publish-records',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrderNewRoute = AppOrderNewRouteImport.update({
  id: '/order/new',
  path: '/order/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderConfirmationOrderIdRoute =
  AppOrderConfirmationOrderIdRouteImport.update({
    id: '/order/confirmation/$orderId',
    path: '/order/confirmation/$orderId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/fulfillment': typeof AppFulfillmentRoute
  '/app/my-orders': typeof AppMyOrdersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offer': typeof AppOfferRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/account-audit': typeof AppAdminAccountAuditRoute
  '/app/admin/accounts': typeof AppAdminAccountsRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/delivery-points': typeof AppAdminDeliveryPointsRoute
  '/app/admin/email-records': typeof AppAdminEmailRecordsRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/mailbox': typeof AppAdminMailboxRoute
  '/app/admin/password-resets': typeof AppAdminPasswordResetsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/team': typeof AppAdminTeamRoute
  '/app/operator/new-batch': typeof AppOperatorNewBatchRoute
  '/app/operator/publish': typeof AppOperatorPublishRoute
  '/app/operator/publish-records': typeof AppOperatorPublishRecordsRoute
  '/app/order/new': typeof AppOrderNewRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/app/order/confirmation/$orderId': typeof AppOrderConfirmationOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/fulfillment': typeof AppFulfillmentRoute
  '/app/my-orders': typeof AppMyOrdersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offer': typeof AppOfferRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/app': typeof AppIndexRoute
  '/app/admin/account-audit': typeof AppAdminAccountAuditRoute
  '/app/admin/accounts': typeof AppAdminAccountsRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/delivery-points': typeof AppAdminDeliveryPointsRoute
  '/app/admin/email-records': typeof AppAdminEmailRecordsRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/mailbox': typeof AppAdminMailboxRoute
  '/app/admin/password-resets': typeof AppAdminPasswordResetsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/team': typeof AppAdminTeamRoute
  '/app/operator/new-batch': typeof AppOperatorNewBatchRoute
  '/app/operator/publish': typeof AppOperatorPublishRoute
  '/app/operator/publish-records': typeof AppOperatorPublishRecordsRoute
  '/app/order/new': typeof AppOrderNewRoute
  '/app/operator': typeof AppOperatorIndexRoute
  '/app/order/confirmation/$orderId': typeof AppOrderConfirmationOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/coupons': typeof AppCouponsRoute
  '/app/fulfillment': typeof AppFulfillmentRoute
  '/app/my-orders': typeof AppMyOrdersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/offer': typeof AppOfferRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/account-audit': typeof AppAdminAccountAuditRoute
  '/app/admin/accounts': typeof AppAdminAccountsRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/delivery-points': typeof AppAdminDeliveryPointsRoute
  '/app/admin/email-records': typeof AppAdminEmailRecordsRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/mailbox': typeof AppAdminMailboxRoute
  '/app/admin/password-resets': typeof AppAdminPasswordResetsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/team': typeof AppAdminTeamRoute
  '/app/operator/new-batch': typeof AppOperatorNewBatchRoute
  '/app/operator/publish': typeof AppOperatorPublishRoute
  '/app/operator/publish-records': typeof AppOperatorPublishRecordsRoute
  '/app/order/new': typeof AppOrderNewRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/app/order/confirmation/$orderId': typeof AppOrderConfirmationOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/app'
    | '/book'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/app/collections'
    | '/app/coupons'
    | '/app/fulfillment'
    | '/app/my-orders'
    | '/app/notifications'
    | '/app/offer'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/security'
    | '/staff/admin'
    | '/staff/forgot-password'
    | '/app/'
    | '/app/admin/account-audit'
    | '/app/admin/accounts'
    | '/app/admin/audit-log'
    | '/app/admin/delivery-points'
    | '/app/admin/email-records'
    | '/app/admin/employees'
    | '/app/admin/mailbox'
    | '/app/admin/password-resets'
    | '/app/admin/settings'
    | '/app/admin/team'
    | '/app/operator/new-batch'
    | '/app/operator/publish'
    | '/app/operator/publish-records'
    | '/app/order/new'
    | '/app/operator/'
    | '/app/order/confirmation/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/book'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/app/collections'
    | '/app/coupons'
    | '/app/fulfillment'
    | '/app/my-orders'
    | '/app/notifications'
    | '/app/offer'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/security'
    | '/staff/admin'
    | '/staff/forgot-password'
    | '/app'
    | '/app/admin/account-audit'
    | '/app/admin/accounts'
    | '/app/admin/audit-log'
    | '/app/admin/delivery-points'
    | '/app/admin/email-records'
    | '/app/admin/employees'
    | '/app/admin/mailbox'
    | '/app/admin/password-resets'
    | '/app/admin/settings'
    | '/app/admin/team'
    | '/app/operator/new-batch'
    | '/app/operator/publish'
    | '/app/operator/publish-records'
    | '/app/order/new'
    | '/app/operator'
    | '/app/order/confirmation/$orderId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/app'
    | '/book'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/app/collections'
    | '/app/coupons'
    | '/app/fulfillment'
    | '/app/my-orders'
    | '/app/notifications'
    | '/app/offer'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/security'
    | '/staff/admin'
    | '/staff/forgot-password'
    | '/app/'
    | '/app/admin/account-audit'
    | '/app/admin/accounts'
    | '/app/admin/audit-log'
    | '/app/admin/delivery-points'
    | '/app/admin/email-records'
    | '/app/admin/employees'
    | '/app/admin/mailbox'
    | '/app/admin/password-resets'
    | '/app/admin/settings'
    | '/app/admin/team'
    | '/app/operator/new-batch'
    | '/app/operator/publish'
    | '/app/operator/publish-records'
    | '/app/order/new'
    | '/app/operator/'
    | '/app/order/confirmation/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  StaffAdminRoute: typeof StaffAdminRoute
  StaffForgotPasswordRoute: typeof StaffForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coupons': {
      id: '/app/coupons'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AppCouponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fulfillment': {
      id: '/app/fulfillment'
      path: '/fulfillment'
      fullPath: '/app/fulfillment'
      preLoaderRoute: typeof AppFulfillmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-orders': {
      id: '/app/my-orders'
      path: '/my-orders'
      fullPath: '/app/my-orders'
      preLoaderRoute: typeof AppMyOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offer': {
      id: '/app/offer'
      path: '/offer'
      fullPath: '/app/offer'
      preLoaderRoute: typeof AppOfferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/staff/admin': {
      id: '/staff/admin'
      path: '/staff/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof StaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/forgot-password': {
      id: '/staff/forgot-password'
      path: '/staff/forgot-password'
      fullPath: '/staff/forgot-password'
      preLoaderRoute: typeof StaffForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/account-audit': {
      id: '/app/admin/account-audit'
      path: '/admin/account-audit'
      fullPath: '/app/admin/account-audit'
      preLoaderRoute: typeof AppAdminAccountAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/accounts': {
      id: '/app/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/app/admin/accounts'
      preLoaderRoute: typeof AppAdminAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit-log': {
      id: '/app/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/app/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/delivery-points': {
      id: '/app/admin/delivery-points'
      path: '/admin/delivery-points'
      fullPath: '/app/admin/delivery-points'
      preLoaderRoute: typeof AppAdminDeliveryPointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/email-records': {
      id: '/app/admin/email-records'
      path: '/admin/email-records'
      fullPath: '/app/admin/email-records'
      preLoaderRoute: typeof AppAdminEmailRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/employees': {
      id: '/app/admin/employees'
      path: '/admin/employees'
      fullPath: '/app/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/mailbox': {
      id: '/app/admin/mailbox'
      path: '/admin/mailbox'
      fullPath: '/app/admin/mailbox'
      preLoaderRoute: typeof AppAdminMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/password-resets': {
      id: '/app/admin/password-resets'
      path: '/admin/password-resets'
      fullPath: '/app/admin/password-resets'
      preLoaderRoute: typeof AppAdminPasswordResetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/team': {
      id: '/app/admin/team'
      path: '/admin/team'
      fullPath: '/app/admin/team'
      preLoaderRoute: typeof AppAdminTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/': {
      id: '/app/operator/'
      path: '/operator'
      fullPath: '/app/operator/'
      preLoaderRoute: typeof AppOperatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/new-batch': {
      id: '/app/operator/new-batch'
      path: '/operator/new-batch'
      fullPath: '/app/operator/new-batch'
      preLoaderRoute: typeof AppOperatorNewBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/publish': {
      id: '/app/operator/publish'
      path: '/operator/publish'
      fullPath: '/app/operator/publish'
      preLoaderRoute: typeof AppOperatorPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/publish-records': {
      id: '/app/operator/publish-records'
      path: '/operator/publish-records'
      fullPath: '/app/operator/publish-records'
      preLoaderRoute: typeof AppOperatorPublishRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/order/new': {
      id: '/app/order/new'
      path: '/order/new'
      fullPath: '/app/order/new'
      preLoaderRoute: typeof AppOrderNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/order/confirmation/$orderId': {
      id: '/app/order/confirmation/$orderId'
      path: '/order/confirmation/$orderId'
      fullPath: '/app/order/confirmation/$orderId'
      preLoaderRoute: typeof AppOrderConfirmationOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCouponsRoute: typeof AppCouponsRoute
  AppFulfillmentRoute: typeof AppFulfillmentRoute
  AppMyOrdersRoute: typeof AppMyOrdersRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOfferRoute: typeof AppOfferRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAccountAuditRoute: typeof AppAdminAccountAuditRoute
  AppAdminAccountsRoute: typeof AppAdminAccountsRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminDeliveryPointsRoute: typeof AppAdminDeliveryPointsRoute
  AppAdminEmailRecordsRoute: typeof AppAdminEmailRecordsRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRoute
  AppAdminMailboxRoute: typeof AppAdminMailboxRoute
  AppAdminPasswordResetsRoute: typeof AppAdminPasswordResetsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTeamRoute: typeof AppAdminTeamRoute
  AppOperatorNewBatchRoute: typeof AppOperatorNewBatchRoute
  AppOperatorPublishRoute: typeof AppOperatorPublishRoute
  AppOperatorPublishRecordsRoute: typeof AppOperatorPublishRecordsRoute
  AppOrderNewRoute: typeof AppOrderNewRoute
  AppOperatorIndexRoute: typeof AppOperatorIndexRoute
  AppOrderConfirmationOrderIdRoute: typeof AppOrderConfirmationOrderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollectionsRoute: AppCollectionsRoute,
  AppCouponsRoute: AppCouponsRoute,
  AppFulfillmentRoute: AppFulfillmentRoute,
  AppMyOrdersRoute: AppMyOrdersRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOfferRoute: AppOfferRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAccountAuditRoute: AppAdminAccountAuditRoute,
  AppAdminAccountsRoute: AppAdminAccountsRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminDeliveryPointsRoute: AppAdminDeliveryPointsRoute,
  AppAdminEmailRecordsRoute: AppAdminEmailRecordsRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRoute,
  AppAdminMailboxRoute: AppAdminMailboxRoute,
  AppAdminPasswordResetsRoute: AppAdminPasswordResetsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTeamRoute: AppAdminTeamRoute,
  AppOperatorNewBatchRoute: AppOperatorNewBatchRoute,
  AppOperatorPublishRoute: AppOperatorPublishRoute,
  AppOperatorPublishRecordsRoute: AppOperatorPublishRecordsRoute,
  AppOrderNewRoute: AppOrderNewRoute,
  AppOperatorIndexRoute: AppOperatorIndexRoute,
  AppOrderConfirmationOrderIdRoute: AppOrderConfirmationOrderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  StaffAdminRoute: StaffAdminRoute,
  StaffForgotPasswordRoute: StaffForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
